### 1. Criar um Gênero
POST http://localhost:3000/generos
Content-Type: application/json

{
  "nome": "Plataforma" 
}

### 2. Criar uma Plataforma de Videogame
POST http://localhost:3000/plataformas
Content-Type: application/json

{
  "nome": "Super Nintendo"
}

### 3. Criar um Jogo
POST http://localhost:3000/jogos
Content-Type: application/json

{
  "titulo": "Super Mario World",
  "idGenero": 1
}

### 4. Relacionar Jogo existente com uma Plataforma
POST http://localhost:3000/jogos/1/plataformas
Content-Type: application/json

{
  "idPlataforma": 1
}

### 5. Listar todos os dados cadastrados
GET http://localhost:3000/jogos


#### 6. Criar outro Jogo
POST http://localhost:3000/jogos
Content-Type: application/json

{
  "titulo": "Sonic the Hedgehog",
  "idGenero": 1,
  "idsPlataformas": [1] 
}